import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'student_list'), ['student_list.c']);
env.Program(os.path.join(BIN_DIR, 'student_list_mvvm'), ['student_list_mvvm.c']);
